DROP TABLE IF EXISTS BILLING_EXTRACT;

CREATE TABLE BILLING_EXTRACT (
    ID INT AUTO_INCREMENT,
    CLIENT_SWIFT_ADDRESS VARCHAR(250),
    SERVICE_NAME VARCHAR(250),
    SUB_SERVICE_NAME VARCHAR(250),
    DATE VARCHAR(250),
    USAGE_STATUS VARCHAR(250),
    PRIMARY KEY (ID)

);